---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Test the proxy
      ansible.builtin.uri:
        url: "http://www.google.com/"
      environment:
        http_proxy: http://localhost:3128
        https_proxy: http://localhost:3128
